const courses = [
    {
        id: 'arendal',
        name: 'Arendal & Omegn Golfklubb',
        logo: '/logos/arendal.webp',
        url: 'https://arendalgk.no',
        lat: 58.4547,
        lon: 8.7660,
        scrapeMethod: 'clubsite',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'asker',
        name: 'Asker Golfklubb',
        logo: '/logos/asker.webp',
        url: 'https://www.askergolf.no',
        lat: 59.8279,
        lon: 10.4388,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'askim',
        name: 'Askim Golfpark',
        logo: '/logos/askim.webp',
        url: 'https://askimgk.no/',
        lat: 59.5953,
        lon: 11.1707,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'atlungstad',
        name: 'Atlungstad Golf',
        logo: '/logos/atlungstad.webp',
        url: 'https://atlungstadgolf.no',
        lat: 60.7586,
        lon: 11.0774,
        scrapeMethod: 'atlungstad',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'ballerud',
        name: 'Ballerud Golfklubb',
        logo: '/logos/ballerud.webp',
        url: 'https://www.ballerud.no',
        lat: 59.9396,
        lon: 10.6297,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'bergen',
        name: 'Bergen Golfklubb',
        logo: '/logos/bergen.avif',
        url: 'https://www.bgk.no/',
        lat: 60.4476,
        lon: 5.3204,
        scrapeMethod: 'bergen',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'bjornefjorden',
        name: 'Bjørnefjorden Golfklubb',
        logo: '/logos/bjornefjorden.webp',
        url: 'https://www.bjgk.no/',
        lat: 60.1913,
        lon: 5.4799,
        scrapeMethod: 'bjornefjorden',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'bjaavann',
        name: 'Bjaavann Golfklubb',
        logo: '/logos/bjaavann.webp',
        url: 'https://bjaavanngk.no',
        lat: 58.1303,
        lon: 8.0403,
        scrapeMethod: 'clubsite',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'bamble',
        name: 'Bamble Golfklubb',
        logo: '/logos/bamble.webp',
        url: 'https://bamblegolfklubb.no',
        lat: 58.9529,
        lon: 9.5891,
        scrapeMethod: 'bamble',
        region: 'Østlandet',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'borre',
        name: 'Borre Golfklubb',
        logo: '/logos/borre.webp',
        url: 'https://www.borregb.no',
        lat: 59.3976,
        lon: 10.4519,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'borregaard',
        name: 'Borregaard Golfklubb',
        logo: '/logos/borregaard.webp',
        url: 'https://borregaardgk.no/',
        lat: 59.2949,
        lon: 11.1288,
        scrapeMethod: 'borregaard',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'baerum',
        name: 'Bærum Golfklubb',
        logo: '/logos/baerum.webp',
        url: 'https://www.bmgk.no',
        lat: 59.8927,
        lon: 10.505,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'drammen',
        name: 'Drammen Golfklubb',
        logo: '/logos/drammen.webp',
        url: 'https://www.drammengk.no',
        lat: 59.67,
        lon: 10.2179,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'drobak',
        name: 'Drøbak Golfklubb',
        logo: '/logos/drobak.webp',
        url: 'https://www.drobakgolf.no/',
        lat: 59.6755,
        lon: 10.6456,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'eiker',
        name: 'Eiker Golfklubb',
        logo: '/logos/eiker.webp',
        url: 'https://www.eikergolf.no',
        lat: 59.736,
        lon: 10.0082,
        scrapeMethod: 'eiker',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'elverum',
        name: 'Elverum Golfklubb',
        logo: '/logos/elverum.webp',
        url: 'https://elverumgolf.no/banestatus/',
        lat: 60.8768,
        lon: 11.6635,
        scrapeMethod: 'elverum',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'egersund',
        name: 'Egersund Golfklubb',
        logo: '/logos/egersund.webp',
        url: 'https://egersund-golfklubb.no/',
        lat: 58.4533,
        lon: 6.0022,
        scrapeMethod: 'egersund',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'floro',
        name: 'Florø Golfklubb',
        logo: '/logos/floro.webp',
        url: 'https://www.florogolf.no/',
        lat: 61.6097,
        lon: 5.1305,
        scrapeMethod: 'news-keywords',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'fana',
        name: 'Fana Golfklubb',
        logo: '/logos/fana.webp',
        url: 'https://fanagolf.no',
        lat: 60.2894,
        lon: 5.3073,
        scrapeMethod: 'clubsite',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'fet',
        name: 'Fet Golfklubb',
        logo: '/logos/fet.webp',
        url: 'https://www.fetgk.no/',
        lat: 59.9163,
        lon: 11.1692,
        scrapeMethod: 'wordpress-banestatus',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'gamle fredrikstad',
        name: 'Gamle Fredrikstad Golfklubb',
        logo: '/logos/gamle_fredrikstad.webp',
        url: 'https://gfgk.no/',
        lat: 59.2013,
        lon: 10.964,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'gjerdrum',
        name: 'Gjerdrum Golfklubb',
        logo: '/logos/gjerdrum.webp',
        url: 'https://www.gjerdrumgolfklubb.no/',
        lat: 60.0624,
        lon: 11.0566,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'gjersjoen',
        name: 'Gjersjøen Golfklubb',
        logo: '/logos/gjersjoen.webp',
        url: 'https://www.gjersjoengolf.no',
        lat: 59.7456,
        lon: 10.789,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'gjoviktoten',
        name: 'Gjøvik og Toten Golfklubb',
        logo: '/logos/gjovik.webp',
        url: 'https://gtgk.no',
        lat: 60.6997,
        lon: 10.7326,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'grenland',
        name: 'Grenland og Omegn Golfklubb',
        logo: '/logos/grenland.webp',
        url: 'https://grenlandgolf.no',
        lat: 59.268,
        lon: 9.5719,
        scrapeMethod: 'squarespace-news',
        region: 'Østlandet',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'grimstad',
        name: 'Grimstad Golfklubb',
        logo: '/logos/grimstad.webp',
        url: 'https://grimstadgolfklubb.no',
        lat: 58.3409,
        lon: 8.5934,
        scrapeMethod: 'clubsite',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'grini',
        name: 'Grini Golfklubb',
        logo: '/logos/grini.webp',
        url: 'https://www.grinigolfklubb.no/',
        lat: 59.9504,
        lon: 10.62265,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'groruddalen',
        name: 'Groruddalen Golfklubb',
        logo: '/logos/groruddalen.webp',
        url: 'https://www.grorudgk.no',
        lat: 59.9668,
        lon: 10.91338,
        scrapeMethod: 'groruddalen',
        region: 'Østlandet',
        county: 'Oslo',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'gronmo',
        name: 'Grønmo Golfklubb',
        logo: '/logos/gronmo.webp',
        url: 'https://www.gronmogk.no/banen/driving-rangen/',
        lat: 59.8431,
        lon: 10.857,
        scrapeMethod: 'gronmo-status',
        region: 'Østlandet',
        county: 'Oslo',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hafjell',
        name: 'Hafjell Golfklubb',
        logo: '/logos/hafjell.webp',
        url: 'https://hafjellgolf.no/',
        lat: 61.2443,
        lon: 10.4542,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'haga',
        name: 'Haga Golfklubb',
        logo: '/logos/haga.webp',
        url: 'https://www.hagagolf.no/',
        lat: 59.9418,
        lon: 10.5766,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 27,
        coursesHoles: [{ match: 'aksjonær', holes: 9 }],
    },
    {
        id: 'halden',
        name: 'Halden Golfklubb',
        logo: '/logos/halden.webp',
        url: 'https://haldengk.no/start/banen/banestatus',
        lat: 59.1182,
        lon: 11.387,
        scrapeMethod: 'halden',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hallingdal',
        name: 'Hallingdal Golfklubb',
        logo: '/logos/hallingdal.webp',
        url: 'https://www.hallingdalgolfklubb.no',
        lat: 60.701,
        lon: 8.3552,
        scrapeMethod: 'hallingdal',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'haugaland',
        name: 'Haugaland Golfklubb',
        logo: '/logos/haugaland.webp',
        url: 'https://haugalandgolf.no/',
        lat: 59.6467,
        lon: 5.5348,
        scrapeMethod: 'haugaland',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'hardanger',
        name: 'Hardanger Golfklubb',
        logo: '/logos/hardanger.webp',
        url: 'https://hardangergolfklubb.no/',
        lat: 60.3755,
        lon: 6.1825,
        scrapeMethod: 'hardanger',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'herdla',
        name: 'Herdla Golfklubb',
        logo: '/logos/herdla.webp',
        url: 'https://herdlagolfklubb.no/',
        lat: 60.5679,
        lon: 4.9527,
        scrapeMethod: 'herdla',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hauger',
        name: 'Hauger Golfklubb',
        logo: '/logos/hauger.webp',
        url: 'https://www.hauger-golfklubb.no/',
        lat: 60.0018,
        lon: 10.981,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'haugesund',
        name: 'Haugesund Golfpark',
        logo: '/logos/haugesund.webp',
        url: 'https://www.haugesundgolf.no/',
        lat: 59.414,
        lon: 5.268,
        scrapeMethod: 'haugesund',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hemsedal',
        name: 'Hemsedal Golfklubb',
        logo: '/logos/hemsedal.webp',
        url: 'https://www.hemsedalgolfklubb.no',
        lat: 60.8676,
        lon: 8.57,
        scrapeMethod: 'hemsedal',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hof',
        name: 'Hof Golfklubb',
        logo: '/logos/hof.webp',
        url: 'https://hofgolfklubb.no',
        lat: 59.5395,
        lon: 10.084,
        scrapeMethod: 'hof',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hovden',
        name: 'Hovden Golfklubb',
        logo: '/logos/hovden.webp',
        url: 'https://hovdengolf.com/',
        lat: 59.5542,
        lon: 7.8411,
        scrapeMethod: 'news-keywords',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'holtsmark',
        name: 'Holtsmark Golfklubb',
        logo: '/logos/holtsmark.webp',
        url: 'https://holtsmarkgolf.no/',
        lat: 59.8706,
        lon: 10.2584,
        scrapeMethod: 'holtsmark',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'huseby',
        name: 'Huseby & Hankø Golfklubb',
        logo: '/logos/huseby.webp',
        url: 'https://www.hhg.no',
        lat: 59.2666,
        lon: 10.7959,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hvaler',
        name: 'Hvaler Golfklubb',
        logo: '/logos/hvaler.webp',
        url: 'https://www.hvalergk.no',
        lat: 59.054,
        lon: 11.0202,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'jaeren',
        name: 'Jæren Golfklubb',
        logo: '/logos/jaren.webp',
        url: 'https://www.jgk.no/',
        lat: 58.7634,
        lon: 5.5518,
        scrapeMethod: 'jaeren',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'kvinnherad',
        name: 'Kvinnherad Golfklubb',
        logo: '/logos/kvinnherad.webp',
        url: 'https://golfen.no/',
        lat: 59.8617,
        lon: 5.7653,
        scrapeMethod: 'kvinnherad',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'kjekstad',
        name: 'Kjekstad Golfklubb',
        logo: '/logos/kjekstad.webp',
        url: 'https://www.kjekstad-gk.no',
        lat: 59.7502,
        lon: 10.3722,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'kongsberg',
        name: 'Kongsberg Golfklubb',
        logo: '/logos/kongsberg.webp',
        url: 'https://kongsberggolf.no/banen/banestatus/',
        lat: 59.6154,
        lon: 9.7126,
        scrapeMethod: 'kongsberg',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'kongsvinger',
        name: 'Kongsvinger Golfklubb',
        logo: '/logos/kongsvinger.webp',
        url: 'https://kongsvingergolf.no',
        lat: 60.1291,
        lon: 12.0509,
        scrapeMethod: 'kongsvinger',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'kristiansand',
        name: 'Kristiansand Golfklubb',
        logo: '/logos/kristiansand.webp',
        url: 'https://kristiansandgk.no',
        lat: 58.1467,
        lon: 7.9956,
        scrapeMethod: 'clubsite',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'kragero',
        name: 'Kragerø Golfklubb',
        logo: '/logos/kragero.webp',
        url: 'https://kragk.no',
        lat: 58.9528,
        lon: 9.1111,
        scrapeMethod: 'clubsite',
        region: 'Vestfold og Telemark',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'karmoy',
        name: 'Karmøy Golfklubb',
        logo: '/logos/karmoy.webp',
        url: 'https://www.karmoy-golfklubb.no/',
        lat: 59.2918,
        lon: 5.2476,
        scrapeMethod: 'karmoy',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'krokhol',
        name: 'Krokhol Golfklubb',
        logo: '/logos/krokhol.webp',
        url: 'https://www.krokhol.no/banen/banestatus/',
        lat: 59.78,
        lon: 10.91,
        scrapeMethod: 'krokhol-sidebar',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'larvik',
        name: 'Larvik Golfklubb',
        logo: '/logos/larvik.webp',
        url: 'https://larvikgolf.no',
        lat: 59.033,
        lon: 10.0071,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'lillestrom',
        name: 'Lillestrøm Golfklubb',
        logo: '/logos/lillestrom.webp',
        url: 'https://lilgk.no/',
        lat: 59.9558,
        lon: 11.0691,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'lindesnes',
        name: 'Lindesnes Golfklubb',
        logo: '/logos/lindesnes.webp',
        url: 'https://lindesnesgolfklubb.no/',
        lat: 58.0297,
        lon: 7.3968,
        scrapeMethod: 'wordpress-banestatus',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'lofoten',
        name: 'Lofoten Links',
        logo: '/logos/lofoten.webp',
        url: 'https://www.lofotenlinks.no/golf/apninstider/',
        lat: 68.3403,
        lon: 14.1256,
        scrapeMethod: 'squarespace-news',
        region: 'Nord-Norge',
        county: 'Nordland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'lommedalen',
        name: 'Lommedalen Golfklubb',
        logo: '/logos/lommedalen.webp',
        url: 'https://www.lommedalengk.no/nyheter',
        lat: 59.98,
        lon: 10.49,
        scrapeMethod: 'squarespace-news',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'losby',
        name: 'Losby Golfklubb',
        logo: '/logos/losby.webp',
        url: 'https://www.losby.no',
        lat: 59.91,
        lon: 10.99,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 27,
    },
    {
        id: 'mandal',
        name: 'Mandal Golfklubb',
        logo: '/logos/mandal.webp',
        url: 'https://mandalgk.no',
        lat: 58.0271,
        lon: 7.4634,
        scrapeMethod: 'mandal',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'miklagard',
        name: 'Miklagard Golfklubb',
        logo: '/logos/miklagard.webp',
        url: 'https://miklagardgolf.no/',
        lat: 60.0784,
        lon: 11.1522,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'meland',
        name: 'Meland Golfklubb',
        logo: '/logos/meland.webp',
        url: 'https://melandgolf.no/',
        lat: 60.5406,
        lon: 5.0864,
        scrapeMethod: 'meland',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'mjosen',
        name: 'Mjøsen Golfklubb',
        logo: '/logos/mjosen.webp',
        url: 'https://msgk.no/',
        lat: 60.9477,
        lon: 10.6996,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'evje',
        name: 'Moss og Rygge Golfklubb (Evje Golfpark)',
        logo: '/logos/evje.webp',
        url: 'https://www.evjegolf.no',
        lat: 59.3687,
        lon: 10.6784,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'mork',
        name: 'Mørk Golfklubb',
        logo: '/logos/mork.webp',
        url: 'https://www.morkgolf.no',
        lat: 59.5318,
        lon: 10.9979,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'nordvegen',
        name: 'Nordvegen Golf',
        logo: '/logos/nordvegen.webp',
        url: 'https://nordvegengolf.no/',
        lat: 59.5233,
        lon: 5.2549,
        scrapeMethod: 'nordvegen',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'nordfjord',
        name: 'Nordfjord Golfklubb',
        logo: '/logos/nordfjord.webp',
        url: 'https://www.norgolf.com/',
        lat: 61.9103,
        lon: 6.0120,
        scrapeMethod: 'nordfjord',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'nes',
        name: 'Nes Golfklubb (Vormsund)',
        logo: '/logos/nes.webp',
        url: 'https://nesgolf.no/',
        lat: 60.1619,
        lon: 11.4215,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'nesbyen',
        name: 'Nesbyen Golfklubb',
        logo: '/logos/nesbyen.webp',
        url: 'https://nesfjellet.no/nb/golfbanen-ny',
        lat: 60.534,
        lon: 9.0221,
        scrapeMethod: 'nesbyen',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'norefjell',
        name: 'Norefjell Golfklubb',
        logo: '/logos/norefjell.webp',
        url: 'https://www.norefjell-golf.no/innstillinger/banestatus',
        lat: 60.1908,
        lon: 9.6039,
        scrapeMethod: 'norefjell-status-page',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'norsjo',
        name: 'Norsjø Golfklubb',
        logo: '/logos/norsjo.webp',
        url: 'https://golfparken.no',
        lat: 59.3016,
        lon: 9.2471,
        scrapeMethod: 'nesbyen',
        region: 'Østlandet',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'notteroy',
        name: 'Nøtterøy Golfklubb',
        logo: '/logos/notteroy.webp',
        url: 'https://notteroygolf.no/banestatus/',
        lat: 59.2259,
        lon: 10.3949,
        scrapeMethod: 'notteroy',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'ogna',
        name: 'Ogna Golfklubb',
        logo: '/logos/ogna.webp',
        url: 'https://ognagolf.no/',
        lat: 58.5542,
        lon: 5.8003,
        scrapeMethod: 'ogna',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'onsoy',
        name: 'Onsøy Golfklubb',
        logo: '/logos/onsoy.webp',
        url: 'https://www.onsoygolfklubb.no',
        lat: 59.2167,
        lon: 10.8167,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'oppegard',
        name: 'Oppegård Golfklubb',
        logo: '/logos/nes.webp',
        url: 'https://oppegardgk.no/',
        lat: 59.777,
        lon: 10.8126,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'oslo',
        name: 'Oslo Golfklubb',
        logo: '/logos/oslo.webp',
        url: 'https://www.oslogk.no/dagens-status',
        lat: 59.9622,
        lon: 10.6362,
        scrapeMethod: 'oslogk',
        region: 'Østlandet',
        county: 'Oslo',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'preikestolen',
        name: 'Preikestolen Golfklubb',
        logo: '/logos/preikestolen.webp',
        url: 'https://www.prgk.no/',
        lat: 58.9883,
        lon: 6.0967,
        scrapeMethod: 'prgk',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'randsfjorden',
        name: 'Randsfjorden Golfklubb',
        logo: '/logos/randsfjord.webp',
        url: 'https://www.randsfjordgolf.no',
        lat: 60.6408,
        lon: 10.367,
        scrapeMethod: 'randsfjord',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'ringerike',
        name: 'Ringerike Golfklubb',
        logo: '/logos/ringerike.webp',
        url: 'https://www.ringerikegk.no',
        lat: 60.3484,
        lon: 10.0988,
        scrapeMethod: 'ringerike',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'rjukan',
        name: 'Rjukan Golfklubb',
        logo: '/logos/rjukan.webp',
        url: 'https://www.rjukangolf.no/banen/',
        lat: 59.9284,
        lon: 8.7598,
        scrapeMethod: 'rjukan',
        region: 'Østlandet',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'romerike',
        name: 'Romerike Golfklubb',
        logo: '/logos/romerike.webp',
        url: 'https://romerikegk.no/blogs/banestatus',
        lat: 59.9372,
        lon: 11.1143,
        scrapeMethod: 'shopify-blog',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'randaberg',
        name: 'Randaberg Golfklubb',
        logo: '/logos/randaberg.webp',
        url: 'https://www.randaberggolf.no/',
        lat: 59.0,
        lon: 5.615,
        scrapeMethod: 'randaberg',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sandane',
        name: 'Sandane Golfklubb',
        logo: '/logos/sandane.webp',
        url: 'https://www.sandanegolf.no/',
        lat: 61.7569,
        lon: 6.2410,
        scrapeMethod: 'sandane',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'selje',
        name: 'Selje Golfklubb',
        logo: '/logos/selje.webp',
        url: 'https://www.seljegolfklubb.no/',
        lat: 62.0400,
        lon: 5.3662,
        scrapeMethod: 'selje',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sande',
        name: 'Sande Golfklubb',
        logo: '/logos/sande.webp',
        url: 'https://www.sandegk.no',
        lat: 59.6121,
        lon: 10.215,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sandefjord',
        name: 'Sandefjord Golfklubb',
        logo: '/logos/sandefjord.webp',
        url: 'https://www.sandefjordgolf.no/banen/banestatus/',
        lat: 59.1064,
        lon: 10.1752,
        scrapeMethod: 'sandefjord',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'sandnes',
        name: 'Sandnes Golfklubb',
        logo: '/logos/sandnes.webp',
        url: 'https://sandnesgolfklubb.no/',
        lat: 58.8717,
        lon: 5.6738,
        scrapeMethod: 'sandnes',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'sirdal',
        name: 'Sirdal Fjellgolfklubb',
        logo: '/logos/sirdal.webp',
        url: 'https://sirdalfjellgolf.no',
        lat: 58.8897,
        lon: 6.6774,
        scrapeMethod: 'sirdal',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'ski',
        name: 'Ski Golfklubb',
        logo: '/logos/ski.webp',
        url: 'https://www.skigk.no',
        lat: 59.72,
        lon: 10.83,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'skjeberg',
        name: 'Skjeberg Golfklubb',
        logo: '/logos/skjeberg.webp',
        url: 'https://www.skjeberggk.no',
        lat: 59.2756,
        lon: 11.1954,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'sauda',
        name: 'Sauda Golfklubb',
        logo: '/logos/sauda.svg',
        url: 'https://www.saudagolf.no/',
        lat: 59.6506,
        lon: 6.3574,
        scrapeMethod: 'sauda',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sotra',
        name: 'Sotra Golfklubb',
        logo: '/logos/sotra.webp',
        url: 'https://sotragk.no/',
        lat: 60.3530,
        lon: 5.0876,
        scrapeMethod: 'clubsite',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'stord',
        name: 'Stord Golfklubb',
        logo: '/logos/stord.avif',
        url: 'https://www.stordgolf.com/',
        lat: 59.8081,
        lon: 5.5150,
        scrapeMethod: 'stord',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sunnfjord',
        name: 'Sunnfjord Golfklubb',
        logo: '/logos/sunnfjord.webp',
        url: 'https://sunnfjordgk.no/',
        lat: 61.4869,
        lon: 6.0800,
        scrapeMethod: 'sunnfjord',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sola',
        name: 'Sola Golfklubb',
        logo: '/logos/sola.webp',
        url: 'https://solagk.no/',
        lat: 58.8847,
        lon: 5.6124,
        scrapeMethod: 'sola',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'solum',
        name: 'Solum Golfklubb',
        logo: '/logos/solum.webp',
        url: 'https://www.solumgolf.club',
        lat: 59.4675,
        lon: 10.3106,
        scrapeMethod: 'squarespace-news',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'soon',
        name: 'Soon Golfklubb',
        logo: '/logos/soon.webp',
        url: 'https://soongolf.no',
        lat: 59.5333,
        lon: 10.6803,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sorknes',
        name: 'Sorknes Golfklubb',
        logo: '/logos/sorknes.webp',
        url: 'https://sorknesgk.no',
        lat: 61.1698,
        lon: 11.3316,
        scrapeMethod: 'sorknes',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'stavanger',
        name: 'Stavanger Golfklubb',
        logo: '/logos/stavanger.webp',
        url: 'https://www.sgk.no/banestatus/',
        lat: 58.958,
        lon: 5.644,
        scrapeMethod: 'sgk',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'tysnes',
        name: 'Tysnes Golfklubb',
        logo: '/logos/tysnes.webp',
        url: 'https://www.tysnesgolf.no/',
        lat: 60.0155,
        lon: 5.5463,
        scrapeMethod: 'tysnes',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'tjome',
        name: 'Tjøme Golfklubb',
        logo: '/logos/tjome.webp',
        url: 'https://www.tjomegolfklubb.no',
        lat: 59.1114,
        lon: 10.3886,
        scrapeMethod: 'tjome',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'tyrifjord',
        name: 'Tyrifjord Golfklubb',
        logo: '/logos/tyrifjord.webp',
        url: 'https://www.tyrifjord-golfklubb.no',
        lat: 60.0521,
        lon: 10.2641,
        scrapeMethod: 'tyrifjord',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'tonsberg',
        name: 'Tønsberg Golfklubb',
        logo: '/logos/tonsberg.webp',
        url: 'https://tonsberggolfklubb.no',
        lat: 59.3333,
        lon: 10.3035,
        scrapeMethod: 'bamble',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'ullensaker',
        name: 'Ullensaker Golfklubb',
        logo: '/logos/ullensaker.webp',
        url: 'https://www.ugk.no/banestatus/',
        lat: 60.1517,
        lon: 11.0955,
        scrapeMethod: 'wordpress-banestatus',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'utsikten',
        name: 'Utsikten Golfklubb',
        logo: '/logos/utsikten.webp',
        url: 'https://utsiktengolf.no',
        lat: 58.9167,
        lon: 9.0667,
        scrapeMethod: 'clubsite',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'valdres',
        name: 'Valdres Golfklubb',
        logo: '/logos/valdres.webp',
        url: 'https://valdresgolf.no',
        lat: 60.9286,
        lon: 9.3523,
        scrapeMethod: 'valdres',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'vestfold',
        name: 'Vestfold Golfklubb',
        logo: '/logos/vestfold.webp',
        url: 'https://vgk.no',
        lat: 59.2436,
        lon: 10.3518,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'voss',
        name: 'Voss Golfklubb',
        logo: '/logos/voss.webp',
        url: 'https://www.vossgolf.no/',
        lat: 60.6820,
        lon: 6.4862,
        scrapeMethod: 'voss',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'vradal',
        name: 'Vrådal Golfklubb',
        logo: '/logos/vradal.webp',
        url: 'https://www.vradalgolfklubb.no',
        lat: 59.317,
        lon: 8.4756,
        scrapeMethod: 'squarespace-news',
        region: 'Østlandet',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'ostmarka',
        name: 'Østmarka Golfklubb',
        logo: '/logos/ostmarka.webp',
        url: 'https://ostmarkagolf.no',
        lat: 59.7234,
        lon: 10.9234,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'aas-gaard',
        name: 'Aas Gaard Golfpak / Hakadal',
        logo: '/logos/aas-gaard.webp',
        url: 'https://www.aasgaardgolfpark.no',
        lat: 60.1311,
        lon: 10.834,
        scrapeMethod: 'coursecond-widget',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
]

module.exports = courses
