const courses = [
    {
        id: 'alsten',
        name: 'Alsten Golfklubb',
        logo: null,
        url: 'https://www.facebook.com/groups/103960416302523',
        lat: 65.978044,
        lon: 12.563716,
        scrapeMethod: 'none',
        mapsCoordOnly: true,
        region: 'Nordland',
        county: 'Nordland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'alta',
        name: 'Alta Golfklubb',
        logo: '/logos/alta.webp',
        url: 'https://www.altagolfklubb.no/',
        lat: 69.9218758,
        lon: 23.0869101,
        scrapeMethod: 'glfr',
        glfrSlug: 'alta-golfklubb',
        region: 'Finnmark',
        county: 'Finnmark',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'arendal',
        name: 'Arendal & Omegn Golfklubb',
        logo: '/logos/arendal.webp',
        url: 'https://arendalgk.no',
        lat: 58.4547,
        lon: 8.7660,
        scrapeMethod: 'clubsite',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'asker',
        name: 'Asker Golfklubb',
        logo: '/logos/asker.webp',
        url: 'https://www.askergolf.no',
        lat: 59.8279,
        lon: 10.4388,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'askim',
        name: 'Askim Golfpark',
        logo: '/logos/askim.webp',
        url: 'https://askimgk.no/',
        lat: 59.5953,
        lon: 11.1707,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'atlungstad',
        name: 'Atlungstad Golf',
        logo: '/logos/atlungstad.webp',
        url: 'https://atlungstadgolf.no',
        lat: 60.7586,
        lon: 11.0774,
        scrapeMethod: 'atlungstad',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'austraat',
        name: 'Austrått Golfklubb',
        logo: '/logos/austraatt.webp',
        url: 'https://www.facebook.com/people/Austr%C3%A5tt-Golfklubb/100063651903196/',
        lat: 63.7074077,
        lon: 9.7268474,
        scrapeMethod: 'none',
        facebookNote: true,
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'ballerud',
        name: 'Ballerud Golfklubb',
        logo: '/logos/ballerud.webp',
        url: 'https://www.ballerud.no',
        lat: 59.9396,
        lon: 10.6297,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'bamble',
        name: 'Bamble Golfklubb',
        logo: '/logos/bamble.webp',
        url: 'https://bamblegolfklubb.no',
        lat: 58.9529,
        lon: 9.5891,
        scrapeMethod: 'generic',
        region: 'Østlandet',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'bergen',
        name: 'Bergen Golfklubb',
        logo: '/logos/bergen.avif',
        url: 'https://www.bgk.no/',
        lat: 60.4476,
        lon: 5.3204,
        scrapeMethod: 'bergen',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'bjornefjorden',
        name: 'Bjørnefjorden Golfklubb',
        logo: '/logos/bjornefjorden.webp',
        url: 'https://www.bjgk.no/',
        lat: 60.1913,
        lon: 5.4799,
        scrapeMethod: 'bjornefjorden',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'bjaavann',
        name: 'Bjaavann Golfklubb',
        logo: '/logos/bjaavann.webp',
        url: 'https://bjaavanngk.no',
        lat: 58.1303,
        lon: 8.0403,
        scrapeMethod: 'clubsite',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'bleik',
        name: 'Bleik Golfstrømbane',
        logo: '/logos/bleik.webp',
        url: 'https://www.facebook.com/BleikGolf/',
        lat: 69.2773191,
        lon: 15.9663939,
        scrapeMethod: 'none',
        region: 'Nordland',
        county: 'Nordland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'bodo',
        name: 'Bodø Golfklubb',
        logo: '/logos/bodo.webp',
        url: 'https://bodogolfklubb.no/',
        lat: 67.2764835,
        lon: 14.7343449,
        scrapeMethod: 'generic',
        region: 'Nordland',
        county: 'Nordland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'borre',
        name: 'Borre Golfklubb',
        logo: '/logos/borre.webp',
        url: 'https://www.borregb.no',
        lat: 59.3976,
        lon: 10.4519,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'borregaard',
        name: 'Borregaard Golfklubb',
        logo: '/logos/borregaard.webp',
        url: 'https://borregaardgk.no/',
        lat: 59.2949,
        lon: 11.1288,
        scrapeMethod: 'borregaard',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'byneset',
        name: 'Byneset Golfklubb',
        logo: '/logos/byneset.webp',
        url: 'https://www.bynesetgolf.no/',
        lat: 63.3545219,
        lon: 10.1525198,
        scrapeMethod: 'byneset',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 27,
        coursesHoles: [
            { match: 'North', holes: 18 },
            { match: 'South', holes: 9 },
        ],
    },
    {
        id: 'baerum',
        name: 'Bærum Golfklubb',
        logo: '/logos/baerum.webp',
        url: 'https://www.bmgk.no',
        lat: 59.8927,
        lon: 10.505,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'dalane',
        name: 'Dalane Golfklubb',
        logo: null,
        url: 'https://www.facebook.com/dalanegk',
        lat: 58.3280064,
        lon: 6.2875113,
        scrapeMethod: 'none',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'drammen',
        name: 'Drammen Golfklubb',
        logo: '/logos/drammen.webp',
        url: 'https://www.drammengk.no',
        lat: 59.67,
        lon: 10.2179,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'drobak',
        name: 'Drøbak Golfklubb',
        logo: '/logos/drobak.webp',
        url: 'https://www.drobakgolf.no/',
        lat: 59.6755,
        lon: 10.6456,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'egersund',
        name: 'Egersund Golfklubb',
        logo: '/logos/egersund.webp',
        url: 'https://egersund-golfklubb.no/',
        lat: 58.4533,
        lon: 6.0022,
        scrapeMethod: 'egersund',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'eiker',
        name: 'Eiker Golfklubb',
        logo: '/logos/eiker.webp',
        url: 'https://www.eikergolf.no',
        lat: 59.736,
        lon: 10.0082,
        scrapeMethod: 'eiker',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'ekholt',
        name: 'Ekholtbruket Golfklubb',
        logo: '/logos/ekholtbruket.webp',
        url: 'https://www.ekholtgolf.no/banen',
        lat: 59.4083207,
        lon: 10.6802698,
        scrapeMethod: 'ekholt',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'elverum',
        name: 'Elverum Golfklubb',
        logo: '/logos/elverum.webp',
        url: 'https://elverumgolf.no/banestatus/',
        lat: 60.8768,
        lon: 11.6635,
        scrapeMethod: 'elverum',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'fana',
        name: 'Fana Golfklubb',
        logo: '/logos/fana.webp',
        url: 'https://fanagolf.no',
        lat: 60.2894,
        lon: 5.3073,
        scrapeMethod: 'clubsite',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'fet',
        name: 'Fet Golfklubb',
        logo: '/logos/fet.webp',
        url: 'https://www.fetgk.no/',
        lat: 59.9163,
        lon: 11.1692,
        scrapeMethod: 'wordpress-banestatus',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'floro',
        name: 'Florø Golfklubb',
        logo: '/logos/floro.webp',
        url: 'https://www.florogolf.no/',
        lat: 61.6097,
        lon: 5.1305,
        scrapeMethod: 'news-keywords',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'frosta',
        name: 'Frosta Golfklubb',
        logo: '/logos/frosta.webp',
        url: 'https://www.frostagk.no/next/p/69912/hjem',
        lat: 63.5830672,
        lon: 10.8007783,
        scrapeMethod: 'generic',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'gamle fredrikstad',
        name: 'Gamle Fredrikstad Golfklubb',
        logo: '/logos/gamle_fredrikstad.webp',
        url: 'https://gfgk.no/',
        lat: 59.2013,
        lon: 10.964,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'giske',
        name: 'Giske Golfklubb',
        logo: '/logos/giske.webp',
        url: 'https://giskegolf.no/',
        lat: 62.5339057,
        lon: 6.1250616,
        scrapeMethod: 'news-keywords',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'gjerdrum',
        name: 'Gjerdrum Golfklubb',
        logo: '/logos/gjerdrum.webp',
        url: 'https://www.gjerdrumgolfklubb.no/',
        lat: 60.0624,
        lon: 11.0566,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'gjersjoen',
        name: 'Gjersjøen Golfklubb',
        logo: '/logos/gjersjoen.webp',
        url: 'https://www.gjersjoengolf.no',
        lat: 59.7456,
        lon: 10.789,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'gjoviktoten',
        name: 'Gjøvik og Toten Golfklubb',
        logo: '/logos/gjovik.webp',
        url: 'https://gtgk.no',
        lat: 60.6997,
        lon: 10.7326,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'grenland',
        name: 'Grenland og Omegn Golfklubb',
        logo: '/logos/grenland.webp',
        url: 'https://grenlandgolf.no',
        lat: 59.268,
        lon: 9.5719,
        scrapeMethod: 'squarespace-news',
        region: 'Østlandet',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'grimstad',
        name: 'Grimstad Golfklubb',
        logo: '/logos/grimstad.webp',
        url: 'https://grimstadgolfklubb.no',
        lat: 58.3409,
        lon: 8.5934,
        scrapeMethod: 'clubsite',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'grini',
        name: 'Grini Golfklubb',
        logo: '/logos/grini.webp',
        url: 'https://www.grinigolfklubb.no/',
        lat: 59.9504,
        lon: 10.62265,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'groruddalen',
        name: 'Groruddalen Golfklubb',
        logo: '/logos/groruddalen.webp',
        url: 'https://www.grorudgk.no',
        lat: 59.9668,
        lon: 10.91338,
        scrapeMethod: 'groruddalen',
        region: 'Østlandet',
        county: 'Oslo',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'gronmo',
        name: 'Grønmo Golfklubb',
        logo: '/logos/gronmo.webp',
        url: 'https://www.gronmogk.no/banen/driving-rangen/',
        lat: 59.8431,
        lon: 10.857,
        scrapeMethod: 'gronmo-status',
        region: 'Østlandet',
        county: 'Oslo',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'gumoygolf',
        name: 'Gumøy Golfklubb',
        logo: null,
        url: 'https://www.facebook.com/people/Gum%C3%B8y-Golf/100057515617097/',
        lat: 58.8900525,
        lon: 9.5133159,
        scrapeMethod: 'none',
        region: 'Østlandet',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hafjell',
        name: 'Hafjell Golfklubb',
        logo: '/logos/hafjell.webp',
        url: 'https://hafjellgolf.no/',
        lat: 61.2443,
        lon: 10.4542,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'haga',
        name: 'Haga Golfklubb',
        logo: '/logos/haga.webp',
        url: 'https://www.hagagolf.no/',
        lat: 59.9418,
        lon: 10.5766,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 27,
        coursesHoles: [
            { match: 'hovedbane', displayName: 'Hovedbane', holes: 18 },
            { match: 'aksjonær', displayName: 'Aksjonærsløyfe', holes: 9 },
        ],
    },
    {
        id: 'halden',
        name: 'Halden Golfklubb',
        logo: '/logos/halden.webp',
        url: 'https://haldengk.no/start/banen/banestatus',
        lat: 59.1182,
        lon: 11.387,
        scrapeMethod: 'halden',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hallingdal',
        name: 'Hallingdal Golfklubb',
        logo: '/logos/hallingdal.webp',
        url: 'https://www.hallingdalgolfklubb.no',
        lat: 60.701,
        lon: 8.3552,
        scrapeMethod: 'hallingdal',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'hammerfest',
        name: 'Hammerfest Golfklubb',
        logo: '/logos/hammerfest.webp',
        url: 'https://www.hammerfestgolf.no/',
        lat: 70.4469459,
        lon: 24.3340041,
        scrapeMethod: 'generic',
        region: 'Finnmark',
        county: 'Finnmark',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'hardanger',
        name: 'Hardanger Golfklubb',
        logo: '/logos/hardanger.webp',
        url: 'https://hardangergolfklubb.no/',
        lat: 60.3755,
        lon: 6.1825,
        scrapeMethod: 'hardanger',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'harstad',
        name: 'Harstad Golfklubb',
        logo: '/logos/harstad.webp',
        url: 'https://hgolf.no/',
        lat: 68.8348234,
        lon: 16.4842543,
        scrapeMethod: 'generic',
        region: 'Troms',
        county: 'Troms',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hasvik',
        name: 'Hasvik Golfklubb',
        logo: '/logos/hasvik.webp',
        url: 'https://www.facebook.com/people/Hasvik-Golfklubb/100057546575354/',
        lat: 70.4960778,
        lon: 22.1348809,
        scrapeMethod: 'none',
        mapsCoordOnly: true,
        facebookNote: true,
        region: 'Finnmark',
        county: 'Finnmark',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'haugaland',
        name: 'Haugaland Golfklubb',
        logo: '/logos/haugaland.webp',
        url: 'https://haugalandgolf.no/',
        lat: 59.6467,
        lon: 5.5348,
        scrapeMethod: 'haugaland',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'hauger',
        name: 'Hauger Golfklubb',
        logo: '/logos/hauger.webp',
        url: 'https://www.hauger-golfklubb.no/',
        lat: 60.0018,
        lon: 10.981,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'haugesund',
        name: 'Haugesund Golfpark',
        logo: '/logos/haugesund.webp',
        url: 'https://www.haugesundgolf.no/',
        lat: 59.414,
        lon: 5.268,
        scrapeMethod: 'haugesund',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'helgeland',
        name: 'Helgeland Golfklubb',
        logo: '/logos/helgeland.webp',
        url: 'https://www.helgelandgolfklubb.no/',
        lat: 65.9260031,
        lon: 13.3127068,
        scrapeMethod: 'none',
        region: 'Nordland',
        county: 'Nordland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hemsedal',
        name: 'Hemsedal Golfklubb',
        logo: '/logos/hemsedal.webp',
        url: 'https://www.hemsedalgolfklubb.no',
        lat: 60.8676,
        lon: 8.57,
        scrapeMethod: 'hemsedal',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'herdla',
        name: 'Herdla Golfklubb',
        logo: '/logos/herdla.webp',
        url: 'https://herdlagolfklubb.no/',
        lat: 60.5679,
        lon: 4.9527,
        scrapeMethod: 'herdla',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hitra',
        name: 'Hitra Frøya Golfklubb',
        logo: '/logos/hitra.webp',
        url: 'https://www.hitragolf.no/',
        lat: 63.5100107,
        lon: 9.0178817,
        scrapeMethod: 'hitra',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hof',
        name: 'Hof Golfklubb',
        logo: '/logos/hof.webp',
        url: 'https://hofgolfklubb.no',
        lat: 59.5395,
        lon: 10.084,
        scrapeMethod: 'hof',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'holtsmark',
        name: 'Holtsmark Golfklubb',
        logo: '/logos/holtsmark.webp',
        url: 'https://holtsmarkgolf.no/',
        lat: 59.8706,
        lon: 10.2584,
        scrapeMethod: 'holtsmark',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'hovden',
        name: 'Hovden Golfklubb',
        logo: '/logos/hovden.webp',
        url: 'https://hovdengolf.com/',
        lat: 59.5542,
        lon: 7.8411,
        scrapeMethod: 'news-keywords',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'huseby',
        name: 'Huseby & Hankø Golfklubb',
        logo: '/logos/huseby.webp',
        url: 'https://www.hhg.no',
        lat: 59.2666,
        lon: 10.7959,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'husoy',
        name: 'Husøy Golfklubb',
        logo: null,
        url: 'https://www.hotellborge.no/husoy-golfklubb/',
        lat: 59.2383546,
        lon: 10.4622462,
        scrapeMethod: 'none',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hvaler',
        name: 'Hvaler Golfklubb',
        logo: '/logos/hvaler.webp',
        url: 'https://www.hvalergk.no',
        lat: 59.054,
        lon: 11.0202,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'hvam',
        name: 'Hvam Golfklubb',
        logo: '/logos/hvam.webp',
        url: 'https://www.facebook.com/groups/1843265482629509/',
        lat: 60.0977008,
        lon: 11.3608192,
        scrapeMethod: 'none',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'jaeren',
        name: 'Jæren Golfklubb',
        logo: '/logos/jaren.webp',
        url: 'https://www.jgk.no/',
        lat: 58.7634,
        lon: 5.5518,
        scrapeMethod: 'jaeren',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'karasjok',
        name: 'Karasjok Golfklubb',
        logo: '/logos/karasjok.webp',
        url: 'https://karasjokgolf.no/',
        lat: 69.4626224,
        lon: 25.513233,
        scrapeMethod: 'generic',
        region: 'Finnmark',
        county: 'Finnmark',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'karmoy',
        name: 'Karmøy Golfklubb',
        logo: '/logos/karmoy.webp',
        url: 'https://www.karmoy-golfklubb.no/',
        lat: 59.2918,
        lon: 5.2476,
        scrapeMethod: 'karmoy',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'kjekstad',
        name: 'Kjekstad Golfklubb',
        logo: '/logos/kjekstad.webp',
        url: 'https://www.kjekstad-gk.no',
        lat: 59.7502,
        lon: 10.3722,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'klabu',
        name: 'Klæbu Golfklubb',
        logo: '/logos/klabu.webp',
        url: 'https://www.klabugolf.no/',
        lat: 63.3264865,
        lon: 10.4790923,
        scrapeMethod: 'klabu',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'kongsberg',
        name: 'Kongsberg Golfklubb',
        logo: '/logos/kongsberg.webp',
        url: 'https://kongsberggolf.no/banen/banestatus/',
        lat: 59.6154,
        lon: 9.7126,
        scrapeMethod: 'kongsberg',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'kongsvinger',
        name: 'Kongsvinger Golfklubb',
        logo: '/logos/kongsvinger.webp',
        url: 'https://kongsvingergolf.no',
        lat: 60.1291,
        lon: 12.0509,
        scrapeMethod: 'kongsvinger',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'kragero',
        name: 'Kragerø Golfklubb',
        logo: '/logos/kragero.webp',
        url: 'https://kragk.no',
        lat: 58.9528,
        lon: 9.1111,
        scrapeMethod: 'clubsite',
        region: 'Vestfold og Telemark',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'kristiansand',
        name: 'Kristiansand Golfklubb',
        logo: '/logos/kristiansand.webp',
        url: 'https://kristiansandgk.no',
        lat: 58.1467,
        lon: 7.9956,
        scrapeMethod: 'clubsite',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'kristiansund',
        name: 'Kristiansund & Omegn Golfklubb',
        logo: '/logos/kristiansund.png',
        url: 'https://kristiansund-golfklubb.no/',
        lat: 63.1108084,
        lon: 7.8503579,
        scrapeMethod: 'generic',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'krokhol',
        name: 'Krokhol Golfklubb',
        logo: '/logos/krokhol.webp',
        url: 'https://www.krokhol.no/banen/banestatus/',
        lat: 59.78,
        lon: 10.91,
        scrapeMethod: 'krokhol-sidebar',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'kvinnherad',
        name: 'Kvinnherad Golfklubb',
        logo: '/logos/kvinnherad.webp',
        url: 'https://golfen.no/',
        lat: 59.8617,
        lon: 5.7653,
        scrapeMethod: 'kvinnherad',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'larvik',
        name: 'Larvik Golfklubb',
        logo: '/logos/larvik.webp',
        url: 'https://larvikgolf.no',
        lat: 59.033,
        lon: 10.0071,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'lillestrom',
        name: 'Lillestrøm Golfklubb',
        logo: '/logos/lillestrom.webp',
        url: 'https://lilgk.no/',
        lat: 59.9558,
        lon: 11.0691,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'lindesnes',
        name: 'Lindesnes Golfklubb',
        logo: '/logos/lindesnes.webp',
        url: 'https://lindesnesgolfklubb.no/',
        lat: 58.0297,
        lon: 7.3968,
        scrapeMethod: 'wordpress-banestatus',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'lofoten',
        name: 'Lofoten Links',
        logo: '/logos/lofoten.webp',
        url: 'https://www.lofotenlinks.no/golf/apninstider/',
        lat: 68.3403,
        lon: 14.1256,
        scrapeMethod: 'squarespace-news',
        region: 'Nord-Norge',
        county: 'Nordland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'lommedalen',
        name: 'Lommedalen Golfklubb',
        logo: '/logos/lommedalen.webp',
        url: 'https://www.lommedalengk.no/nyheter',
        lat: 59.98,
        lon: 10.49,
        scrapeMethod: 'squarespace-news',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'losby',
        name: 'Losby Golfklubb',
        logo: '/logos/losby.webp',
        url: 'https://www.losby.no',
        lat: 59.91,
        lon: 10.99,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 27,
        coursesHoles: [
            { match: 'østmork', displayName: 'Østmork', holes: 18 },
            { match: 'vestmork', displayName: 'Vestmork', holes: 9 },
        ],
    },
    {
        id: 'mandal',
        name: 'Mandal Golfklubb',
        logo: '/logos/mandal.webp',
        url: 'https://mandalgk.no',
        lat: 58.0271,
        lon: 7.4634,
        scrapeMethod: 'mandal',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'meland',
        name: 'Meland Golfklubb',
        logo: '/logos/meland.webp',
        url: 'https://melandgolf.no/',
        lat: 60.5406,
        lon: 5.0864,
        scrapeMethod: 'meland',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'midt-troms',
        name: 'Midt-Troms Golfklubb',
        logo: '/logos/midt-troms.webp',
        url: 'https://www.facebook.com/midttromsgolf/',
        lat: 68.9886857,
        lon: 18.515323,
        scrapeMethod: 'none',
        facebookNote: true,
        region: 'Troms',
        county: 'Troms',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'miklagard',
        name: 'Miklagard Golfklubb',
        logo: '/logos/miklagard.webp',
        url: 'https://miklagardgolf.no/',
        lat: 60.0784,
        lon: 11.1522,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'mjosen',
        name: 'Mjøsen Golfklubb',
        logo: '/logos/mjosen.webp',
        url: 'https://msgk.no/',
        lat: 60.9477,
        lon: 10.6996,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'molde',
        name: 'Molde Golfklubb',
        logo: '/logos/molde.webp',
        url: 'https://moldegolf.no/',
        lat: 62.7530803,
        lon: 7.2413067,
        scrapeMethod: 'clubsite',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'evje',
        name: 'Moss og Rygge Golfklubb (Evje Golfpark)',
        logo: '/logos/evje.webp',
        url: 'https://www.evjegolf.no',
        lat: 59.3687,
        lon: 10.6784,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'mork',
        name: 'Mørk Golfklubb',
        logo: '/logos/mork.webp',
        url: 'https://www.morkgolf.no',
        lat: 59.5318,
        lon: 10.9979,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'namdal',
        name: 'Namdal Golfklubb',
        logo: '/logos/namdal.webp',
        url: 'https://www.facebook.com/groups/425737610801146',
        lat: 64.490771,
        lon: 11.9913037,
        scrapeMethod: 'none',
        facebookNote: true,
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'namsos',
        name: 'Namsos Golfklubb',
        logo: '/logos/namsos.webp',
        url: 'https://www.facebook.com/groups/300787436671666/',
        lat: 64.4293061,
        lon: 11.4745388,
        scrapeMethod: 'none',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'narvik',
        name: 'Narvik Golfklubb',
        logo: '/logos/narvik.webp',
        url: 'https://www.narvikgolf.no/',
        lat: 68.2406099,
        lon: 17.4104856,
        scrapeMethod: 'generic',
        region: 'Nordland',
        county: 'Nordland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'nes',
        name: 'Nes Golfklubb (Vormsund)',
        logo: '/logos/nes.webp',
        url: 'https://nesgolf.no/',
        lat: 60.1619,
        lon: 11.4215,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'nesbyen',
        name: 'Nesbyen Golfklubb',
        logo: '/logos/nesbyen.webp',
        url: 'https://nesfjellet.no/nb/golfbanen-ny',
        lat: 60.534,
        lon: 9.0221,
        scrapeMethod: 'nesbyen',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'nordfjord',
        name: 'Nordfjord Golfklubb',
        logo: '/logos/nordfjord.webp',
        url: 'https://www.norgolf.com/',
        lat: 61.9103,
        lon: 6.0120,
        scrapeMethod: 'nordfjord',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'nordhaug',
        name: 'Nordhaug Golfklubb',
        logo: '/logos/nordhaug.webp',
        url: 'https://nordhauggk.no/',
        lat: 59.9374752,
        lon: 10.5554874,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'nordvegen',
        name: 'Nordvegen Golf',
        logo: '/logos/nordvegen_new.webp',
        url: 'https://nordvegengolf.no/',
        lat: 59.5233,
        lon: 5.2549,
        scrapeMethod: 'nordvegen',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'norefjell',
        name: 'Norefjell Golfklubb',
        logo: '/logos/norefjell.webp',
        url: 'https://www.norefjell-golf.no/innstillinger/banestatus',
        lat: 60.1908,
        lon: 9.6039,
        scrapeMethod: 'norefjell-status-page',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'norsjo',
        name: 'Norsjø Golfklubb',
        logo: '/logos/norsjo.webp',
        url: 'https://golfparken.no',
        lat: 59.3016,
        lon: 9.2471,
        scrapeMethod: 'nesbyen',
        region: 'Østlandet',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'north-cape',
        name: 'North Cape Golf Club',
        logo: '/logos/north-cape.webp',
        url: 'https://northcape-golfclub.no/',
        lat: 70.0748185,
        lon: 24.9097032,
        scrapeMethod: 'generic',
        mapsName: 'Banak Links Golfpark',
        region: 'Finnmark',
        county: 'Finnmark',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'naroysund',
        name: 'Nærøysund Golfklubb',
        logo: '/logos/naroysund.avif',
        url: 'https://www.naroysundgolf.no/',
        lat: 64.8563251,
        lon: 11.2944057,
        scrapeMethod: 'none',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'notteroy',
        name: 'Nøtterøy Golfklubb',
        logo: '/logos/notteroy.webp',
        url: 'https://notteroygolf.no/banestatus/',
        lat: 59.2259,
        lon: 10.3949,
        scrapeMethod: 'notteroy',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'ogna',
        name: 'Ogna Golfklubb',
        logo: '/logos/ogna.webp',
        url: 'https://ognagolf.no/',
        lat: 58.5542,
        lon: 5.8003,
        scrapeMethod: 'ogna',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'onsoy',
        name: 'Onsøy Golfklubb',
        logo: '/logos/onsoy.webp',
        url: 'https://www.onsoygolfklubb.no',
        lat: 59.2167,
        lon: 10.8167,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'oppdal',
        name: 'Oppdal Golfklubb',
        logo: '/logos/oppdal.webp',
        url: 'https://www.oppdalgolfklubb.no/',
        lat: 62.5955394,
        lon: 9.7063703,
        scrapeMethod: 'oppdal',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'oppegard',
        name: 'Oppegård Golfklubb',
        logo: '/logos/nes.webp',
        url: 'https://oppegardgk.no/',
        lat: 59.777,
        lon: 10.8126,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'oslo',
        name: 'Oslo Golfklubb',
        logo: '/logos/oslo.webp',
        url: 'https://www.oslogk.no/dagens-status',
        lat: 59.9622,
        lon: 10.6362,
        scrapeMethod: 'oslogk',
        region: 'Østlandet',
        county: 'Oslo',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'oustoen',
        name: 'Oustøen Country Club',
        logo: '/logos/oustoen.webp',
        url: 'https://occ.no/',
        lat: 59.8687352,
        lon: 10.5785875,
        scrapeMethod: 'none',
        statusNote: 'Klubben er privat og du må være invitert for å spille eller benytte klubbens fasiliteter.',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'polarsirkelen',
        name: 'Polarsirkelen Golfklubb',
        logo: '/logos/polarsirkelen.webp',
        url: 'https://www.polarsirkelen-golf.no/',
        lat: 66.3115912,
        lon: 13.9785742,
        scrapeMethod: 'generic',
        region: 'Nordland',
        county: 'Nordland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'preikestolen',
        name: 'Preikestolen Golfklubb',
        logo: '/logos/preikestolen.webp',
        url: 'https://www.prgk.no/',
        lat: 58.9883,
        lon: 6.0967,
        scrapeMethod: 'prgk',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'randaberg',
        name: 'Randaberg Golfklubb',
        logo: '/logos/randaberg.webp',
        url: 'https://www.randaberggolf.no/',
        lat: 59.0,
        lon: 5.615,
        scrapeMethod: 'randaberg',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'randsfjorden',
        name: 'Randsfjorden Golfklubb',
        logo: '/logos/randsfjord.webp',
        url: 'https://www.randsfjordgolf.no',
        lat: 60.6408,
        lon: 10.367,
        scrapeMethod: 'randsfjord',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'rauma',
        name: 'Rauma Golfklubb',
        logo: '/logos/rauma.webp',
        url: 'https://www.raumagolf.no/next/page/hjem',
        lat: 62.5498872,
        lon: 7.6901454,
        scrapeMethod: 'news-keywords',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'ringerike',
        name: 'Ringerike Golfklubb',
        logo: '/logos/ringerike.webp',
        url: 'https://www.ringerikegk.no',
        lat: 60.3484,
        lon: 10.0988,
        scrapeMethod: 'ringerike',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'rjukan',
        name: 'Rjukan Golfklubb',
        logo: '/logos/rjukan.webp',
        url: 'https://www.rjukangolf.no/banen/',
        lat: 59.9284,
        lon: 8.7598,
        scrapeMethod: 'rjukan',
        region: 'Østlandet',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'romerike',
        name: 'Romerike Golfklubb',
        logo: '/logos/romerike.webp',
        url: 'https://romerikegk.no/blogs/banestatus',
        lat: 59.9372,
        lon: 11.1143,
        scrapeMethod: 'shopify-blog',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'rfgc',
        name: 'Rygge Flystasjon Golfklubb',
        logo: '/logos/rygge.webp',
        url: 'https://rfgc.no/',
        lat: 59.3830155,
        lon: 10.7666437,
        scrapeMethod: 'news-keywords',
        statusNote: 'Gjestespill: På grunn av banens beliggenhet er gjestespill utfordrende, men ikke umulig. Tilgang til flystasjonen, og dermed golfbanen, må ordnes i god tid i forkant, og enhver gjest må eskorteres av et fullverdig medlem til enhver tid. Styret i klubben kan være behjelpelige med dette – ta kontakt på styret@rfgc.no',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'roros',
        name: 'Røros Golfklubb',
        logo: '/logos/roros.webp',
        url: 'https://www.rorosgolf.no/',
        lat: 62.5894368,
        lon: 11.3578315,
        scrapeMethod: 'roros',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'salten',
        name: 'Salten Golfklubb',
        logo: '/logos/salten.webp',
        url: 'https://bodogolfpark.com/',
        lat: 67.3434095,
        lon: 14.5352544,
        scrapeMethod: 'generic',
        region: 'Nordland',
        county: 'Nordland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'sandane',
        name: 'Sandane Golfklubb',
        logo: '/logos/sandane.webp',
        url: 'https://www.sandanegolf.no/',
        lat: 61.7569,
        lon: 6.2410,
        scrapeMethod: 'sandane',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sande',
        name: 'Sande Golfklubb',
        logo: '/logos/sande.webp',
        url: 'https://www.sandegk.no',
        lat: 59.6121,
        lon: 10.215,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sandefjord',
        name: 'Sandefjord Golfklubb',
        logo: '/logos/sandefjord.webp',
        url: 'https://www.sandefjordgolf.no/banen/banestatus/',
        lat: 59.1064,
        lon: 10.1752,
        scrapeMethod: 'sandefjord',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'sandnes',
        name: 'Sandnes Golfklubb',
        logo: '/logos/sandnes.webp',
        url: 'https://sandnesgolfklubb.no/',
        lat: 58.8717,
        lon: 5.6738,
        scrapeMethod: 'sandnes',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'sauda',
        name: 'Sauda Golfklubb',
        logo: '/logos/sauda.svg',
        url: 'https://www.saudagolf.no/',
        lat: 59.6506,
        lon: 6.3574,
        scrapeMethod: 'sauda',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'selje',
        name: 'Selje Golfklubb',
        logo: '/logos/selje.webp',
        url: 'https://www.seljegolfklubb.no/',
        lat: 62.0400,
        lon: 5.3662,
        scrapeMethod: 'selje',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sirdal',
        name: 'Sirdal Fjellgolfklubb',
        logo: '/logos/sirdal.webp',
        url: 'https://sirdalfjellgolf.no',
        lat: 58.8897,
        lon: 6.6774,
        scrapeMethod: 'sirdal',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'skei',
        name: 'Skei Golfklubb',
        logo: '/logos/skei.webp',
        url: 'https://www.skeigolf.no/',
        lat: 61.3361903,
        lon: 10.0900076,
        scrapeMethod: 'news-keywords',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'ski',
        name: 'Ski Golfklubb',
        logo: '/logos/ski.webp',
        url: 'https://www.skigk.no',
        lat: 59.72,
        lon: 10.83,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'skjeberg',
        name: 'Skjeberg Golfklubb',
        logo: '/logos/skjeberg.webp',
        url: 'https://www.skjeberggk.no',
        lat: 59.2756,
        lon: 11.1954,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Østfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'sleneset',
        name: 'Sleneset Golfklubb',
        logo: '/logos/sleneset.webp',
        url: 'https://slenesetgolf.no/',
        lat: 66.3624632,
        lon: 12.5944089,
        scrapeMethod: 'generic',
        region: 'Nordland',
        county: 'Nordland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'smola',
        name: 'Smøla Golfklubb',
        logo: '/logos/smola.webp',
        url: 'https://www.smolagolfklubb.no/',
        lat: 63.4228893,
        lon: 7.8560041,
        scrapeMethod: 'news-keywords',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sola',
        name: 'Sola Golfklubb',
        logo: '/logos/sola.webp',
        url: 'https://solagk.no/',
        lat: 58.8847,
        lon: 5.6124,
        scrapeMethod: 'sola',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'solum',
        name: 'Solum Golfklubb',
        logo: '/logos/solum.webp',
        url: 'https://www.solumgolf.club',
        lat: 59.4675,
        lon: 10.3106,
        scrapeMethod: 'squarespace-news',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'soon',
        name: 'Soon Golfklubb',
        logo: '/logos/soon.webp',
        url: 'https://soongolf.no',
        lat: 59.5333,
        lon: 10.6803,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sorknes',
        name: 'Sorknes Golfklubb',
        logo: '/logos/sorknes.webp',
        url: 'https://sorknesgk.no',
        lat: 61.1698,
        lon: 11.3316,
        scrapeMethod: 'sorknes',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'sotra',
        name: 'Sotra Golfklubb',
        logo: '/logos/sotra.webp',
        url: 'https://sotragk.no/',
        lat: 60.3530,
        lon: 5.0876,
        scrapeMethod: 'clubsite',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'stavanger',
        name: 'Stavanger Golfklubb',
        logo: '/logos/stavanger.webp',
        url: 'https://www.sgk.no/banestatus/',
        lat: 58.958,
        lon: 5.644,
        scrapeMethod: 'sgk',
        region: 'Vestlandet',
        county: 'Rogaland',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'steinkjer',
        name: 'Steinkjer Golfklubb',
        logo: '/logos/steinkjer.webp',
        url: 'https://steinkjer-golfklubb.no/',
        lat: 64.0138681,
        lon: 11.4924356,
        scrapeMethod: 'none',
        mapsName: 'Midjo golfbane',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'stiklestad',
        name: 'Stiklestad Golfklubb',
        logo: '/logos/stiklestad.webp',
        url: 'https://www.stiklestad-golfklubb.no/',
        lat: 63.8196745,
        lon: 11.4128338,
        scrapeMethod: 'generic',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'stjordal',
        name: 'Stjørdal Golfklubb',
        logo: '/logos/stjordal.webp',
        url: 'https://stjordal.golf/',
        lat: 63.4861475,
        lon: 10.9242693,
        scrapeMethod: 'generic',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'stord',
        name: 'Stord Golfklubb',
        logo: '/logos/stord.avif',
        url: 'https://www.stordgolf.com/',
        lat: 59.8081,
        lon: 5.5150,
        scrapeMethod: 'stord',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'stranda',
        name: 'Stranda Golfklubb',
        logo: '/logos/stranda.webp',
        url: 'https://strandagolf.no/',
        lat: 62.2095334,
        lon: 6.9189774,
        scrapeMethod: 'news-keywords',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sunndal',
        name: 'Sunndal Golfklubb',
        logo: '/logos/sunndal.webp',
        url: 'https://www.sunndal-golfklubb.no/',
        lat: 62.662491,
        lon: 8.5293672,
        scrapeMethod: 'generic',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'sunnfjord',
        name: 'Sunnfjord Golfklubb',
        logo: '/logos/sunnfjord.webp',
        url: 'https://sunnfjordgk.no/',
        lat: 61.4869,
        lon: 6.0800,
        scrapeMethod: 'sunnfjord',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'sunnmore',
        name: 'Sunnmøre Golfklubb',
        logo: '/logos/sunnmore.webp',
        url: 'https://sunnmoregolf.no/',
        lat: 62.351649,
        lon: 5.9660553,
        scrapeMethod: 'news-keywords',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'surnadal',
        name: 'Surnadal Golfklubb',
        logo: '/logos/surnadal.webp',
        url: 'https://surnadal-golfklubb.no/',
        lat: 62.8977121,
        lon: 8.5606016,
        scrapeMethod: 'generic',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'tingvoll',
        name: 'Tingvoll Golfklubb',
        logo: '/logos/tingvoll.webp',
        url: 'https://tingvollgolf.no/',
        lat: 63.0097717,
        lon: 7.996171,
        scrapeMethod: 'tingvoll',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'tjome',
        name: 'Tjøme Golfklubb',
        logo: '/logos/tjome.webp',
        url: 'https://www.tjomegolfklubb.no',
        lat: 59.1114,
        lon: 10.3886,
        scrapeMethod: 'tjome',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'trollstigen',
        name: 'Trollstigen og Geirangerfjorden Golfklubb',
        logo: '/logos/trollstigen.webp',
        url: 'https://www.trollgolf.no/',
        lat: 62.209450,
        lon: 6.920154,
        scrapeMethod: 'news-keywords',
        mapsCoordOnly: true,
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'tromso',
        name: 'Tromsø Golfklubb',
        logo: '/logos/tromso.webp',
        url: 'https://tromsogolf.com/',
        lat: 69.6580149,
        lon: 19.610761,
        scrapeMethod: 'tromso',
        region: 'Troms',
        county: 'Troms',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'trondheim',
        name: 'Trondheim Golfklubb',
        logo: '/logos/trondheim.webp',
        url: 'https://www.golfklubben.no/',
        lat: 63.4213784,
        lon: 10.331354,
        scrapeMethod: 'trondheim-gk',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'trondheim-par3',
        name: 'Trondheim Par3 Golf',
        logo: '/logos/trondheim-par3.webp',
        url: 'https://www.trondheimpar3golf.no/',
        lat: 63.4069575,
        lon: 10.3649402,
        scrapeMethod: 'generic',
        region: 'Trøndelag',
        county: 'Trøndelag',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'trysil',
        name: 'Trysil Golf',
        logo: '/logos/trysil.webp',
        url: 'https://trysilgolf.no/start',
        lat: 61.299703,
        lon: 12.2419122,
        scrapeMethod: 'trysil',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'tyrifjord',
        name: 'Tyrifjord Golfklubb',
        logo: '/logos/tyrifjord.webp',
        url: 'https://www.tyrifjord-golfklubb.no',
        lat: 60.0521,
        lon: 10.2641,
        scrapeMethod: 'tyrifjord',
        region: 'Østlandet',
        county: 'Buskerud',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'tysnes',
        name: 'Tysnes Golfklubb',
        logo: '/logos/tysnes.webp',
        url: 'https://www.tysnesgolf.no/',
        lat: 60.0155,
        lon: 5.5463,
        scrapeMethod: 'tysnes',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'tonsberg',
        name: 'Tønsberg Golfklubb',
        logo: '/logos/tonsberg.webp',
        url: 'https://tonsberggolfklubb.no',
        lat: 59.3333,
        lon: 10.3035,
        scrapeMethod: 'generic',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'ullensaker',
        name: 'Ullensaker Golfklubb',
        logo: '/logos/ullensaker.webp',
        url: 'https://www.ugk.no/banestatus/',
        lat: 60.1517,
        lon: 11.0955,
        scrapeMethod: 'wordpress-banestatus',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'utsikten',
        name: 'Utsikten Golfklubb',
        logo: '/logos/utsikten.webp',
        url: 'https://utsiktengolf.no',
        lat: 58.9167,
        lon: 9.0667,
        scrapeMethod: 'clubsite',
        region: 'Sørlandet',
        county: 'Agder',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'valdres',
        name: 'Valdres Golfklubb',
        logo: '/logos/valdres.webp',
        url: 'https://valdresgolf.no',
        lat: 60.9286,
        lon: 9.3523,
        scrapeMethod: 'valdres',
        region: 'Østlandet',
        county: 'Innlandet',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'vanylven',
        name: 'Vanylven Golfklubb',
        logo: '/logos/vanylven.webp',
        url: 'https://www.vangolf.no/',
        lat: 62.1122337,
        lon: 5.6562527,
        scrapeMethod: 'generic',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'varanger',
        name: 'Varanger Golfklubb',
        logo: '/logos/varanger.webp',
        url: 'https://varangergolf.no/',
        lat: 70.1102859,
        lon: 29.366069,
        scrapeMethod: 'generic',
        region: 'Finnmark',
        county: 'Finnmark',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'veierland',
        name: 'Veierland Golfklubb',
        logo: null,
        url: 'https://www.facebook.com/groups/289659609256387/',
        lat: 59.1649479,
        lon: 10.3497269,
        scrapeMethod: 'none',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 6,
    },
    {
        id: 'vesteralen',
        name: 'Vesterålen Golfklubb',
        logo: '/logos/vesteralen.webp',
        url: 'https://www.vestgolf.com/',
        lat: 68.661943,
        lon: 15.4784758,
        scrapeMethod: 'generic',
        region: 'Nordland',
        county: 'Nordland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'vestfold',
        name: 'Vestfold Golfklubb',
        logo: '/logos/vestfold.webp',
        url: 'https://vgk.no',
        lat: 59.2436,
        lon: 10.3518,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Vestfold',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'volda',
        name: 'Volda Golfklubb',
        logo: '/logos/volda.webp',
        url: 'https://voldagolf.no/index.php',
        lat: 62.1399732,
        lon: 6.1302597,
        scrapeMethod: 'generic',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'voss',
        name: 'Voss Golfklubb',
        logo: '/logos/voss.webp',
        url: 'https://www.vossgolf.no/',
        lat: 60.6820,
        lon: 6.4862,
        scrapeMethod: 'voss',
        region: 'Vestlandet',
        county: 'Vestland',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'vradal',
        name: 'Vrådal Golfklubb',
        logo: '/logos/vradal.webp',
        url: 'https://www.vradalgolfklubb.no',
        lat: 59.317,
        lon: 8.4756,
        scrapeMethod: 'squarespace-news',
        region: 'Østlandet',
        county: 'Telemark',
        timezone: 'Europe/Oslo',
        holes: 9,
    },
    {
        id: 'ostmarka',
        name: 'Østmarka Golfklubb',
        logo: '/logos/ostmarka.webp',
        url: 'https://ostmarkagolf.no',
        lat: 59.7234,
        lon: 10.9234,
        scrapeMethod: 'clubsite',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'alesund',
        name: 'Ålesund Golfklubb',
        logo: '/logos/alesund.webp',
        url: 'https://aalesundgk.no/',
        lat: 62.4850007,
        lon: 6.7235683,
        scrapeMethod: 'clubsite',
        region: 'Vestlandet',
        county: 'Møre og Romsdal',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
    {
        id: 'aas-gaard',
        name: 'Aas Gaard Golfpak / Hakadal',
        logo: '/logos/aas-gaard.webp',
        url: 'https://www.aasgaardgolfpark.no',
        lat: 60.1311,
        lon: 10.834,
        scrapeMethod: 'coursecond-widget',
        region: 'Østlandet',
        county: 'Akershus',
        timezone: 'Europe/Oslo',
        holes: 18,
    },
]

module.exports = courses
